FROM gcc:latest

WORKDIR /app

# Установить зависимости
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    libboost-all-dev \
    libcurl4-openssl-dev \
    libjsoncpp-dev \
    libgtest-dev \
    git \
    --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Собрать и установить Google Test
WORKDIR /usr/src/gtest
RUN cmake . && \
    make && \
    cp lib/*.a /usr/lib

WORKDIR /app

# Копируем CMakeLists.txt
COPY CMakeLists.txt /app/

# Копируем все директории проекта
COPY pgw_server/ /app/pgw_server/
COPY pgw_client/ /app/pgw_client/
COPY pgw_flood_client/ /app/pgw_flood_client/

# Собираем тесты
RUN mkdir -p build && \
    cd build && \
    cmake -DBUILD_TESTS=ON .. && \
    make

# Команда для запуска тестов
CMD ["bash", "-c", "cd build && ctest --output-on-failure"] 